#!/bin/sh
set -eu pipefail

if [ "$1" = "configure" ] || [ "$1" = "triggered" ]; then
    # Prefer LeiOS as the default dpkg vendor.
    if [ ! -e "$DPKG_ROOT/etc/dpkg/origins/default" ] || \
       [ "$(readlink -f "$DPKG_ROOT/etc/dpkg/origins/default" 2>/dev/null)" != "$DPKG_ROOT/etc/dpkg/origins/leios" ]; then
        ln -sf leios "$DPKG_ROOT/etc/dpkg/origins/default"
    fi

    if [ -x "$DPKG_ROOT/usr/share/leios/system/utils/base-files/install.sh" ]; then
        "$DPKG_ROOT/usr/share/leios/system/utils/base-files/install.sh"
    fi
fi

#DEBHELPER#
