#!/bin/sh
set -eu pipefail

PACKAGE="leios.system.base-files"

if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then

    for f in /usr/lib/os-release /etc/lsb-release /etc/issue /etc/issue.net /etc/legal /etc/motd; do
        dpkg-divert --package "$PACKAGE" --add --rename \
            --divert "${f}.base-files" "$f" || true
    done
fi

#DEBHELPER#
